app/controllers/catalog_admin/containers_controller.rb
app/views/catalog_admin/containers/_common_form_fields.html.erb

Fixed page containers creation in the right language group

---

app/models/search/decimal_strategy.rb
app/models/search/email_strategy.rb
app/models/search/int_strategy.rb
app/views/advanced_searches/_decimal_search_field.html.erb
app/views/advanced_searches/_email_search_field.html.erb
app/views/advanced_searches/_int_search_field.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml

resolves #15
Added text_field in _email_search_field.html.erb to avoid having email fields validations (@, ...)

Add new fields in advanced searches

---

app/controllers/catalog_admin/item_types_controller.rb
app/helpers/fields_helper.rb
app/models/item_type.rb
app/views/catalog_admin/item_types/_common_form_fields.html.erb
app/views/items/show.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
db/migrate/20180220093412_add_hide_empty_fields_to_item_types.rb
db/structure.sql
test/fixtures/item_types.yml
test/fixtures/items.yml
test/integration/items_test.rb

Request for this feature was made for a specific catalog, but can be applied project-wide with this pull request.

Add empty fields option (item type)

---

app/policies/user_policy.rb
test/integration/catalog_admin/users_test.rb

test use-case in this pull request is not directly testing the fixed feature, but was missing anyway

Fixed catalog admin edit user role bug & added edit user role test

---

app/javascript/bundles/TranslatedTextField/components/TranslatedTextField.jsx

@christiankaiser I could use your input on this. It solves the bug, but I'm not sure it's the right "react" way to fix the issue.
resolves #25

Fixed "Menu items" & "Pages" title fields not updating

---

app/presenters/field/image_presenter.rb

Size option for thumbnails

---

app/models/search/image_strategy.rb
test/models/search/image_strategy_test.rb

Added image legend in search data

---

app/assets/stylesheets/webpack/date-time-input/date-time-input.css
app/javascript/bundles/DateTimeInput/components/DateTimeInput.jsx
app/models/field/date_time.rb
app/presenters/field/date_time_presenter.rb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
test/models/field/date_time_test.rb
test/presenters/field/date_time_presenter_test.rb

@christiankaiser can you please check that the changes suit you ?
It will modify the output of the DateTime field, but seems to me it's the most flexible way to do things for the catalog editors.
I had to modify some tests for this, can you check if in your opinion it's not breaking things (value_as_int function) ?
Thanks.

Allow nil values for datetime

---

app/presenters/item_view_presenter.rb

Needed for the Viatimages catalog

Added "a" tag to item presenter whitelist

---

app/controllers/catalog_admin/items_controller.rb
app/helpers/application_helper.rb
app/policies/item_policy.rb
app/views/catalog_admin/choice_sets/index.html.erb
app/views/catalog_admin/fields/_table.html.erb
app/views/catalog_admin/items/index.html.erb
app/views/catalog_admin/menu_items/index.html.erb
app/views/catalog_admin/pages/index.html.erb
app/views/catalog_admin/users/index.html.erb
app/views/shared/_actions_dropdown.html.erb
app/views/shared/dropdown/_choiceset.html.erb
app/views/shared/dropdown/_field.html.erb
app/views/shared/dropdown/_item.html.erb
app/views/shared/dropdown/_menuitem.html.erb
app/views/shared/dropdown/_page.html.erb
app/views/shared/dropdown/_user.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
config/routes.rb
test/integration/catalog_admin/choice_sets_test.rb
test/integration/catalog_admin/items_test.rb
test/integration/catalog_admin/pages_test.rb

+ Replaced buttons by dropdown

Added duplication option for items in data mode

---

app/presenters/field/date_time_presenter.rb

@christiankaiser this fix should avoid any datetime presenter errors, can you check if it's ok with you and merge it please ?
Can you also push the changes to production asap, so we can get rid of this bug ? Thanks

Fixed datetime presenter bug with old formats

---

app/assets/stylesheets/modules/env.scss
app/helpers/application_helper.rb
app/views/layouts/base.html.erb

- In development
- In production with a system_admin user

Added environment clue throughout the views

---

app/controllers/items_controller.rb
app/helpers/item_lists_helper.rb
app/views/items/index.html.erb
app/views/items/show.html.erb
app/views/shared/navbar/_navbar_user.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml

Added "View more" translation
Removed "Back to Catima" button in user settings
(needed for Lexic'Art project)

Customize page title based on field being browsed

---

app/helpers/items_helper.rb
app/models/field.rb

Added gard clause to exclude_base64 function

Reverted changes to items_helper function item_display_name

---

.gitignore
Gemfile
Gemfile.lock

Add gems for Windows to Gemfile
Remove unicorn and unicorn-worker-killer only for Windows

Add ability to run the project on Windows

---

app/assets/stylesheets/modules/form.scss
app/controllers/api/v2/items_controller.rb
app/javascript/bundles/ReferenceEditor/components/MultiReferenceEditor.jsx
app/javascript/bundles/ReferenceEditor/components/ReferenceEditor.jsx
app/javascript/bundles/ReferenceEditor/components/SingleReferenceEditor.jsx
app/models/field.rb
app/models/field/boolean.rb
app/models/field/choice_set.rb
app/models/field/date_time.rb
app/models/field/editor.rb
app/models/field/file.rb
app/models/field/geometry.rb
app/models/field/reference.rb
app/models/field/xref.rb
app/models/item.rb
app/models/item/values.rb
app/presenters/field/date_time_presenter.rb
app/presenters/field/editor_presenter.rb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
package.json
test/fixtures/fields.yml
test/fixtures/items.yml
test/integration/catalog_admin/items_reference_selection_test.rb
test/integration/catalog_admin/items_test.rb
test/support/item_reference_helper.rb
yarn.lock

Add SingleReferenceEditor search element
Add SingleReferenceEditor secondary search option
Add MultipleReferenceEditor search inputs for each column
Add MultipleReferenceEditor secondary search option
Improve styles

Improve SingleReferenceEditor and MultipleReferenceEditor components

---

app/helpers/catalog_admin/fields_option_helper.rb
app/views/catalog_admin/fields/_common_form_fields.erb
app/views/catalog_admin/fields/_text_option_inputs.html.erb
test/integration/catalog_admin/fields_primary_test.rb

Remove primary checkbox for non human_readable fields & formatted tex…
Added tests

Fix primary option

---

app/assets/javascripts/catalog-admin/fields.coffee
app/helpers/fields_helper.rb
app/helpers/items_helper.rb
app/models/field.rb
app/models/field/int.rb
app/models/item.rb
app/models/item/values.rb
app/presenters/field/text_presenter.rb
app/views/catalog_admin/fields/_common_form_fields.erb
app/views/catalog_admin/fields/_int_option_inputs.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
test/fixtures/fields.yml
test/integration/catalog_admin/csv_imports_test.rb
test/integration/catalog_admin/fields_primary_test.rb
test/integration/catalog_admin/fields_restricted_test.rb

Added js for primary & formatted text

Fix for "default value" & "autoincrement" options

---

app/models/field.rb
app/models/field/boolean.rb
app/models/field/choice_set.rb
app/models/field/editor.rb
app/models/field/file.rb
app/models/field/geometry.rb
app/models/field/image.rb
app/models/field/reference.rb
app/views/catalog_admin/fields/_choice_set_option_inputs.html.erb
app/views/catalog_admin/fields/_common_form_fields.erb

Removed non-pertinent field options

---

app/javascript/bundles/GeoViewer/components/GeoViewer.jsx

Hotfix: map was not appearing when viewing an item

Fix item map display

---

app/assets/javascripts/catalog-admin/items.coffee
app/controllers/api/v1/catalogs_controller.rb
app/controllers/api/v1/items_controller.rb
app/controllers/api/v2/catalogs_controller.rb
app/controllers/api/v2/fields_controller.rb
app/controllers/api/v2/items_controller.rb
app/controllers/api/v2/users_controller.rb
app/models/catalog.rb
app/models/field/file.rb
app/presenters/field/file_presenter.rb
config/environments/production.rb
config/locales/de.yml
config/locales/en.yml
config/locales/fr.yml
config/locales/it.yml
config/routes.rb
test/integration/api/v1/items_test.rb

Adding upload size restrictions for the File fields

Adding constraints to the API routes

---

app/controllers/api/v2/fields_controller.rb
app/javascript/bundles/AdvancedChoiceSetSearch/components/ChoiceSetSearch.jsx
app/models/search/choice_set_strategy.rb
app/models/search/date_time_strategy.rb

Fix for https://github.com/catima/catima/issues/222

Fix bug with date advanced search with category field

---

app/controllers/advanced_searches_controller.rb
app/controllers/catalog_admin/advanced_search_configurations_controller.rb
app/models/advanced_search_configuration.rb
app/models/item_type.rb
app/views/catalog_admin/advanced_search_configurations/index.html.erb

Fix bug if custom search is used with deleted item type
Fix bug if custom search is used with deleted field
Fix custom search create bug

Fix custom search bugs

---

Gemfile.lock

related to issue https://github.com/puma/puma/issues/2304

Update puma gem to fix failing installation on MacOS

---

app/assets/stylesheets/bootsrap_fixes/index.scss
app/assets/stylesheets/bootstrap_custom.scss
app/assets/stylesheets/modules/pagination.scss
app/assets/stylesheets/modules/table.scss
app/assets/stylesheets/webpack/template-editor/RichEditor.css
app/views/items/_list.html.erb
app/views/items/_thumbnails.html.erb
app/views/searches/_list.html.erb

Fix issue #300:
- rollback thumbnail class and copy style from bs3
- migrate .panel => .card
- only underscore first item of menu
- fix media list (thumbnail margin right + buttons on new line)
- use BS3 container breakdown sizes

fix styles inconsistencies

---

app/assets/stylesheets/bootstrap_custom.scss

#300 Reduce navbar item spaces

---

app/views/documentation/_accordion_item.html.erb

[https://github.com/catima/catima/issues/303](https://github.com/catima/catima/issues/303)

#303 Help Collapse Not Working

---

app/assets/stylesheets/webpack/reference-editor/reference-editor.css
app/javascript/bundles/ReferenceEditor/components/SingleReferenceEditor.jsx

[https://github.com/catima/catima/issues/306](https://github.com/catima/catima/issues/306)

#306 reference field single value display

---

app/assets/stylesheets/bootsrap_fixes/index.scss

[https://github.com/catima/catima/issues/305](https://github.com/catima/catima/issues/305)

#305 Two X Icons

---

app/assets/stylesheets/bootstrap_custom.scss
app/models/item.rb

[https://github.com/catima/catima/issues/311](https://github.com/catima/catima/issues/311)
erroneous `self` removal during migration 
`assign_default_values` and `assign_autoincrement_values` metod fixed  `self` added

#311 Integer Field Auto Increment

---

app/controllers/catalog_admin/choices_controller.rb
app/models/choice_set.rb
app/models/search/choice_set_strategy.rb
app/presenters/field/choice_set_presenter.rb
test/unit/presenters/field/choice_set_presenter_test.rb

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/catima/catima/commit/07bc9425477fda6fb65043744af1bf2f0dfa279a).

Apply fixes from CodeFactor

---

app/views/catalog_admin/choices/edit.html.erb

fix redirection link [https://github.com/catima/catima/issues/319](https://github.com/catima/catima/issues/319)

fix Hierarchical Choice Set

---

app/javascript/bundles/AdvancedChoiceSetSearch/components/ChoiceSetSearch.jsx

https://github.com/catima/catima/issues/326

#326 Redundancy In Advanced Search

---

app/assets/javascripts/catalog-admin/items.coffee
app/views/catalog_admin/items/_choice_modal_forms.html.erb

https://github.com/catima/catima/issues/327

#327 Choice Set Field In A Category

---

app/assets/javascripts/catalog-admin/items.coffee
app/helpers/json_helper.rb
app/models/field.rb
app/models/item_type.rb
app/presenters/field/boolean_presenter.rb
app/presenters/field/choice_set_presenter.rb
app/presenters/field/file_presenter.rb
app/presenters/field/reference_presenter.rb
app/presenters/field_presenter.rb

https://github.com/catima/catima/issues/322

#322 multiple values choice set linked to a category

---

app/helpers/json_helper.rb

https://github.com/catima/catima/issues/338

#338-Missing_Fields

---

app/assets/javascripts/catalog-admin.js
app/controllers/catalog_admin/catalogs_controller.rb
app/helpers/catalog_admin/catalogs_helper.rb
app/models/ahoy/event.rb
app/policies/catalog_policy.rb
app/views/catalog_admin/catalogs/stats.html.erb
app/views/catalog_admin/catalogs/stats/_catalog.html.erb
app/views/layouts/catalog_admin/setup.html.erb
config/locales/app/fr.yml
config/routes.rb

#179267501 Catalog Stats

---

app/controllers/admin/catalogs_controller.rb
app/models/catalog.rb
app/models/category.rb
app/models/choice.rb
app/models/choice_set.rb
app/models/concerns/catalog/clone.rb
app/models/concerns/category/clone.rb
app/models/concerns/choice/clone.rb
app/models/concerns/choice_set/clone.rb
app/models/concerns/item_type/clone.rb
app/models/concerns/menu_item/clone.rb
app/models/concerns/page/clone.rb
app/models/item_type.rb
app/models/menu_item.rb
app/models/page.rb
app/policies/catalog_policy.rb
app/views/shared/actions/_catalog.html.erb
config/routes.rb
test/models/catalog_test.rb

#179280402 Catalog Clone

---

app/controllers/admin/catalogs_controller.rb
app/models/concerns/catalog/clone.rb
app/policies/catalog_policy.rb
app/services/catalog_cloner.rb
app/views/admin/catalogs/duplicate_new.html.erb
app/views/shared/actions/_catalog.html.erb
config/routes.rb
test/models/catalog_test.rb

Fix catalog clone

---

app/models/choice_set.rb

#179868963 Fix Destroy Catalog

---

app/assets/stylesheets/webpack/choice-set/choice-set.css
app/assets/stylesheets/webpack/reference-editor/reference-editor.css

- ensure menu is over other inputs
- ensure menu is over map
- ensure datepicker is over other inputs
issue https://github.com/catima/catima/issues/393

Fix z-index issue on advanced search:

---

app/models/field/compound.rb
app/presenters/field/choice_set_presenter.rb
app/presenters/field/compound_presenter.rb
app/services/dump/sql_dump.rb
app/views/api/v3/catalog/item_type/items/_item.json.jbuilder

Compound Field CR Exports and API

---

app/assets/stylesheets/webpack/reference-editor/reference-editor.css

Fix choice set displayed under the map

---

app/javascript/components/ComplexDatationInput/components/ComplexDatationInput.jsx
app/models/field/complex_datation.rb

@lucaguindani  hello voici in petit fix pour complex_datations updates

Complex_datation_fix

---

app/controllers/catalog_admin/choices_controller.rb
app/javascript/components/ComplexDatationInput/components/ComplexDatationInput.jsx
app/presenters/choice_presenter.rb

Complex_datation_fix2

---

app/controllers/catalog_admin/csv_imports_controller.rb
config/locales/app/en.yml
config/locales/app/fr.yml

Display an error for the following exception:
Unhandled error
Encoding::UndefinedConversionError: "\x9D" to UTF-8 in conversion from Windows-1252 to UTF-8
Location
app/models/csv_import/item_builder.rb:71 - save!

Import csv conversion error

---

app/helpers/catalog_admin/fields_option_helper.rb
app/models/field.rb
app/models/field/image.rb
db/migrate/20221221153045_disable_field_public_list_view_if_formatted_text.rb

Migrations are already run on staging, so data are incorrect.

Fix pictures not displayed in public list display

---

app/javascript/components/ChoiceSetInput/components/ChoiceSetInput.jsx
app/javascript/components/ChoiceSetInput/module/validation.js
app/models/field/choice_set.rb

fix - add validation error to choice_set_input

---

app/models/search/complex_datation_strategy.rb

Comportement du sauf changé pour les complex-datation en recherche avancée pour un choice-set

Change negate in complex datation strategy for choice set complex datation

---

.github/workflows/lighthouse.yml
lighthouserc.js
test/controllers/home_controller.rb
test/fixtures/catalogs.yml

Reports are uploaded as gha artifacts.

Add Lighthouse Github Actions integration

---

app/models/field/embed.rb
config/locales/app/de.yml
config/locales/app/en.yml
config/locales/app/fr.yml
config/locales/app/it.yml
test/integration/fields_test.rb

Fix embed fields validation when no domains are set

Fix embed fields validation
